version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "3000:443"
    volumes:
      - nginx-sync-icon:/var/www/html/icon:nocopy
      - nginx-sync-api:/var/www/html/api:nocopy
      - laravel-docker-vendor-sync:/var/www/html/api/vendor:nocopy
     - ./nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php
      - mysqldb
      - mongodb
  php:
    image: php:7.2-fpm
    build:
      context: ./etc/php-fpm
    restart: always
    volumes:
      - nginx-sync-icon:/var/www/html/icon:nocopy
      - nginx-sync-api:/var/www/html/api:nocopy
      - laravel-docker-vendor-sync:/var/www/html/api/vendor:nocopy
      - ./php-fpm/php7.2.ini:/usr/local/etc/php/php.ini:cached
  mysqldb:
    image: mariadb:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: cement_master
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: icon
      MYSQL_PASSWORD: Password!123
    volumes:
      - ../data/mysql:/var/lib/mysql
    command: mysqld --sql_mode=""
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mongodb:
    image: mongo:3.6.9
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: 48500229ea7596d
  nginx:
    image: shakyshane/nginx-cors-plus
    ports:
      - 8090:80
    environment:
      - TARGET=http://api2.cement.localhost
volumes:
  nginx-sync-icon:
    external: true
  nginx-sync-api:
    external: true
  laravel-docker-vendor-sync:
    external: true

